

BUSINESSES_SHORTHAND = {
    "A": ["ACMOORE", "AGIR", "AMAZO"],
    "B": ["BADDAD", "BNBO", "BOJANG", "BUFF"],
    "C": ["CASAG", "CHICK", "CHICKENSALADCH", "COOKOUT", "CRACKERB", "CVS"],
    "D": ["DOLLARTREE", "DEPTED", "DICKSSP"],
    "E": ["EDISONSQUARE", "ELAMIG", "ELVAL", "ETSY"],
    "F": ["FAMILYVID", "FOODLION"],
    "G": ["GAM", "GATE", "GEI"],
    "H": ["HARDEE", "HARRIST", "HOB"],
    "I": ["IKEA"],
    "J": ["JOHNNYSFARM"],
    "K": ["KFC"],
    "L": ["LOWESF"],
    "M": ["MARSHA", "MCDON", "MURPHYE"],
    "N": ["NEWHOPE", "NINETY"],
    "O": ["OLDN"],
    "P": ["PAPAJOHN", "PAND", "PANE", "PAYP", "PETSMA", "PSNC", "PUN"],
    "Q": ["QUIK"],
    "R": ["REDB", "ROSS"],
    "S": ["SHELL", "SONIC", "SMOO", "STARBUCK", "SUBW", "SWEETFR"],
    "T": ["TACOBELL", "TARG", "TIJ", "TRLAW", "TWC"],
    "U": ["UNCLEMAD"],
    "V": ["VZ"],
    "W": ["WALM", "WMSUP"],
    "7": ["7ELEV"]
}

BUSINESS_DETAILS = {
    "ACMOORE": ("AC Moore", "Entertainment"),
    "AGIR": ("AGI Renter's Insurance", "Homeowning"),
    "AMAZO": ("Amazon.com Purchase", "Entertainment"),
    "BADDAD": ("Bad Daddy's Burger Bar", "Eating Out"),
    "BNBO": ("Barnes & Noble Bookstore", "Entertainment"),
    "BOJANG": ("Bojangles", "Eating Out"),
    "BUFF": ("Buffalo Wild Wings", "Eating Out"),
    "CASAG": ("Casa Grande", "Eating Out"),
    "CHICK": ("Chick-Fil-A", "Eating Out"),
    "CHICKENSALADCH": ("Chicken Salad Chick", "Eating Out"),
    "COOKOUT": ("Cook Out", "Eating Out"),
    "CRACKERB": ("Cracker Barrel", "Eating Out"),
    "CVS": ("CVS Pharmacy", "Medical"),
    "DOLLARTREE": ("Dollar Tree", "Other"),
    "DEPTED": ("Student Loan Payment", "Loans"),
    "DICKSSP": ("Dicks Sporting Goods", "Entertainment"),
    "EDISONSQUARE": ("Edison Square Family Medicine", "Medical"),
    "ELAMIG": ("El Amigo Restaurant", "Eating Out"),
    "ELVAL": ("El Vallarta", "Eating Out"),
    "ETSY": ("Etsy.com", "Entertainment"),
    "FAMILYVID": ("Family Video", "Entertainment"),
    "FOODLION": ("Food Lion", "Grocery"),
    "GAM": ("Gamestop", "Entertainment"),
    "GATE": ("Gate Gas Station", "Vehicle"),
    "GEI": ("Geico", "Vehicle"),
    "HARDEE": ("Hardees", "Eating Out"),
    "HARRIST": ("Harris Teeter", "Grocery"),
    "HOB": ("Hobby Lobby", "Homegoods"),
    "IKEA": ("Ikea", "Homegoods"),
    "JOHNNYSFARM": ("Johnny's Farmhouse", "Eating Out"),
    "KFC": ("Kentucky Fried Chicken", "Eating Out"),
    "LOWESF": ("Lowe's Foods", "Grocery"),
    "MARSHA": ("Marshalls", "Homegoods"),
    "MCDON": ("McDonald's", "Eating Out"),
    "MURPHYE": ("Murphy Express Gas Station", "Vehicle"),
    "NEWHOPE": ("New Hope Worship Center", "Tithing"),
    "NINETY": ("Ninetys Ice Cream", "Coffee/Sweets"),
    "OLDN": ("Old Navy", "Clothing"),
    "PAPAJOHN": ("Papa John's Pizza", "Eating Out"),
    "PAND": ("Panda Express", "Eating Out"),
    "PANE": ("Panera Bread", "Eating Out"),
    "PAYP": ("Paypal", "Homegoods"),
    "PETSMA": ("Petsmart", "Pets"),
    "PSNC": ("PSNC Energy", "Homeowning"),
    "PUN": ("Punchy's Diner", "Eating Out"),
    "QUIK": ("Quiktrip", "Vehicle"),
    "REDB": ("Redbox", "Entertainment"),
    "ROSS": ("Ross", "Clothing"),
    "SHELL": ("Shell Gas Station", "Vehicle"),
    "SONIC": ("Sonic Drive-In", "Eating Out"),
    "SMOO": ("Smoothie King", "Eating Out"),
    "STARBUCK": ("Starbucks", "Coffee/Sweets"),
    "SUBW": ("Subway Restaurant", "Eating Out"),
    "SWEETFR": ("Sweet Frog", "Coffee/Sweets"),
    "TACOBELL": ("Taco Bell", "Eating Out"),
    "TARG": ("Target", "Entertainment"),
    "TIJ": ("Tijuana Flats", "Eating Out"),
    "TRLAW": ("T. R. Lawing Realty", "Homeowning"),
    "TWC": ("Time Warner Cable", "Homeowning"),
    "UNCLEMAD": ("Uncle Maddio's Pizza", "Eating Out"),
    "VZ": ("Verizon Wireless", "Phone"),
    "WALM": ("Wal-Mart", "Grocery"),
    "WMSUP": ("Walmart Supercenter", "Grocery"),
    "7ELEV": ("7-Eleven Gas Station", "Vehicle")
}
